[package]
name = "byteyarn"
version = "0.3.0"
description = "hyper-compact strings"

edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true