[package]
name = "buf-trait"
version = "0.4.1"
description = "abstract over [u8], str, and friends"

edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
zerocopy = "0.7"
